### ISSUE TITLE
Tarea finalizada

### ISSUE THREAD

**Issue by LAS1819** [interfacesweb-19-20/guia-estilos-LAS1819#2]
@pedroprieto , ya he terminado la tarea, espero que esté más o menos bien. Dime si me ha faltado algo.

¡Saludos!

**Comment by pedroprieto** [comment]
Buen trabajo, Luís. Y bonito logo!! 

Te he hecho un par de comentarios en el código. 

Enhorabuena, tienes un 10! :+1:
